(define (fib n)
  (define (iter n f)
    (if (= n 1)
	(f 0 1)
	(iter (- n 1)
	      (lambda (a b)
		(f b (+ a b))))))
  (iter n (lambda (n1 n0) n0)))

(define (fib n)
  (define (rec n f)
    (if (<= n 2)
	(f 1)
	(rec (- n 1)
	     (lambda (a)
	       (rec (- n 2)
		    (lambda (b)
		      (f (+ a b))))))))
  (rec n (lambda (a) a)))

