(defun kmp-match (str p)
  (if (> (length p) 0)
    (let ((next-array (loop for i from 2 below (length p)
                            with arr = (make-array (1+ (length p)) :fill-pointer 2 :initial-element 0)
                            do (vector-push (if (equal (char p (1- i)) (char p (aref arr (1- i)))) 
                                              (1+ (aref arr (1- i))) 
                                              0)
                                            arr)
                            finally (return arr))))
      (labels ((match (start)
                      (loop for i from start below (length str)
                            and c across p
                            until (not (equal c (char str i)))
                            finally (return (cond 
                                              ((>= (- i start)  (length p)) start)
                                              ((= start (- (length str) (length p))) nil)
                                              (t (match (+ start 1 (aref next-array (- i start))))))))))
        (match 0)))))
